baseurl = "http://ganlhi.space/"
languageCode = "fr-fr"
title = "Ganlhi Space"
theme = "hugo_theme_robust"

[Params]
  AuthorMail = "ganlhi@gmail.com"
  Author = "Guilhem Brouat"
  disqusShortname = "Ganlhi"
  DateForm = "02/01/2006"