baseurl = "https://ganlhi.github.io"
languageCode = "fr-fr"
title = "Ganlhi Space"
theme = "hugo_theme_robust"

[Params]
  Author = "Guilhem Brouat"
  disqusShortname = "Ganlhi"
  DateForm = "02/01/2006"