baseurl = "https://ganlhi.gitlab.io/ganlhispace/"
languageCode = "fr-fr"
title = "Ganlhi Space"
theme = "hugo_theme_robust"

[Params]
  Author = "Guilhem Brouat"
  disqusShortname = "Ganlhi"
  DateForm = "02/01/2006"